title: 软件咨询师、全栈开发工程师、IT培训师
description: Eason Li
theme: jekyll-theme-minimal
logo: https://avatars3.githubusercontent.com/u/20301767?s=460&v=4
name: 张三
phone: 15342349100
email: 1534349100@163.com
address: 湖北省武汉市江夏区
school: 湖北工业大学
profession: 信息管理与信息系统
degree: 本科学士学位
credential: 英语四级/计算机三级
